source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/ZYComponent/ZYSpecs.git'

use_frameworks!

target 'ZYSpecialKit_Category_Example' do
  pod 'ZYSpecialKit_Category', :path => '../'

  target 'ZYSpecialKit_Category_Tests' do
    inherit! :search_paths

    
  end
end
